language: ruby
cache: bundler
rvm:
  - 2.2

gemfile:
  - Gemfile

matrix:
  include:
    - rvm: 2.2
      gemfile: gemfiles/rails40.gemfile

    - rvm: 2.2
      gemfile: gemfiles/rails41.gemfile

    - rvm: 2.2
      gemfile: gemfiles/rails42.gemfile

    - rvm: 2.2
      gemfile: gemfiles/rails5.gemfile