language: ruby
cache: bundler

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database pgrel_test;' -U postgres
  - cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
  - "cd spec/dummy && bundle exec rake db:migrate && cd ../.."

matrix:
  include:
    - rvm: 2.2.1
      gemfile: gemfiles/rails5.gemfile