language: ruby
cache: bundler

addons:
  postgresql: "9.4"

before_script:
  - createdb pgrel
  - psql -U postgres -d pgrel -c 'CREATE EXTENSION IF NOT EXISTS hstore;'

matrix:
  include:
    - rvm: 2.5.0
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails5.gemfile
    - rvm: 2.3.2
      gemfile: gemfiles/rails42.gemfile
