# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc960980546c12ad91ecf8aa9d650c50566483f54c3d216b9662b31feba7df0101fd8891a169854f21a6e92e7a57c02c32f06497d8faf45afaa4855bbf7f4fb8

test:
  secret_key_base: d3bc7c9eb460dc0f8a2b330cc4b96a26028da6548352013f824f1bcd53693c2e32f9c19f83deff2a9c192225d1eb200563d77a5d852b6dfba3faf85e757fe020

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
